### ISSUE TITLE
Update GitHub Actions workflow

### ISSUE THREAD

**Issue by obervinov** [obervinov/messages-package#7]
- [x] Tests and checks workflow - run on the main branch for the show badge
- [x] Add workflow with package installation verification (by tag, branch, default)
- [x] Merge all workflows to single file
    ```yaml
    name: Test, Build and create relese

    on:
      push:
        branches:    
          - '*'
          - '*/*'
          - '**'

    env:
      PROJECT_DESCRIPTION: "This project is a telegram bot that allows you to create backups of content from your Instagram profile to Dropbox or Mega clouds, as well as in the local file system."


    jobs:
      pylint:
        uses: obervinov/_templates/.github/workflows/test.pylint.yml@v1.0.4
      verify-changelog:
        uses: obervinov/_templates/.github/workflows/verify.changelog.yml@v1.0.4
      pytest:
        uses: obervinov/_templates/.github/workflows/test.pytest-with-vault.yml@v1.0.4
      build-release:
        uses: obervinov/_templates/.github/workflows/build.docker.yml@release/v1.0.5
        needs: [pylint, verify-changelog, pytest]
    ```
- [x] Fix the error that caused the workflow create_release to run twice - at pr/main
    ![](https://user-images.githubusercontent.com/49606362/247088581-67edc88d-8cdb-4076-9b17-8b7185a330b0.png)
